In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [ ]:
import scipy.stats

In [ ]:
import math

In [5]:
url='https://github.com/WalePhenomenon/climate_change/blob/master/fuel_ferc1.csv?raw=true'
fuel_details = pd.read_csv(url, error_bad_lines=False)
fuel_details.describe(include='all')

,record_id,utility_id_ferc1,report_year,plant_name_ferc1,fuel_type_code_pudl,fuel_unit,fuel_qty_burned,fuel_mmbtu_per_unit,fuel_cost_per_unit_burned,fuel_cost_per_unit_delivered,fuel_cost_per_mmbtu
count,29523,29523.000000,29523.000000,29523,29523,29343,2.952300e+04,29523.000000,29523.000000,2.952300e+04,29523.000000
unique,29523,NaN,NaN,2315,6,9,NaN,NaN,NaN,NaN,NaN
top,f1_fuel_2015_12_186_1_1,NaN,NaN,big stone,gas,mcf,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,156,11486,11354,NaN,NaN,NaN,NaN,NaN
mean,NaN,118.601836,2005.806050,NaN,NaN,NaN,2.622119e+06,8.492111,208.649031,9.175704e+02,19.304354
std,NaN,74.178353,7.025483,NaN,NaN,NaN,9.118004e+06,10.600220,2854.490090,6.877593e+04,2091.540939
min,NaN,1.000000,1994.000000,NaN,NaN,NaN,1.000000e+00,0.000001,-276.080000,-8.749370e+02,-41.501000
25%,NaN,55.000000,2000.000000,NaN,NaN,NaN,1.381700e+04,1.024000,5.207000,3.778500e+00,1.940000
50%,NaN,122.000000,2006.000000,NaN,NaN,NaN,2.533220e+05,5.762694,26.000000,1.737100e+01,4.127000
75%,NaN,176.000000,2012.000000,NaN,NaN,NaN,1.424034e+06,17.006000,47.113000,4.213700e+01,7.745000
max,NaN,514.000000,2018.000000,NaN,NaN,NaN,5.558942e+08,341.260000,139358.000000,7.964521e+06,359278.000000

In [ ]:
# Question 1

In [6]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]

In [7]:
A_B = A.extend(B)
print(A_B)

None

In [8]:
A_B = A.append(B)
print(A_B)

None

In [ ]:
# None of the above can be used to create list

In [9]:
# Question 2

In [10]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.array([1,0,0],[0,1,0],[0,0,1])

ValueError: only 2 non-keyword arguments accepted

In [12]:
eye(3)

NameError: name 'eye' is not defined

In [13]:
np.array[(1,0,0),(0,1,0),(0,0,1)]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [14]:
# From the given options, only np.array(3) is correct

In [15]:
# Question 3

In [16]:
new_fuel_details = fuel_details.dropna()

In [17]:
new_fuel_details.describe()

,utility_id_ferc1,report_year,fuel_qty_burned,fuel_mmbtu_per_unit,fuel_cost_per_unit_burned,fuel_cost_per_unit_delivered,fuel_cost_per_mmbtu
count,29343.000000,29343.000000,2.934300e+04,29343.000000,29343.000000,2.934300e+04,29343.000000
mean,118.507037,2005.819105,2.609171e+06,8.477481,209.756592,9.230343e+02,18.543975
std,74.241226,7.019855,8.798699e+06,10.537478,2863.194789,6.898652e+04,2097.367750
min,1.000000,1994.000000,1.000000e+00,0.000001,-276.080000,-8.749370e+02,-41.501000
25%,55.000000,2000.000000,1.375050e+04,1.024000,5.230000,3.793000e+00,1.950000
50%,122.000000,2006.000000,2.524640e+05,5.763072,26.039000,1.749000e+01,4.140000
75%,176.000000,2012.000000,1.424218e+06,17.000000,47.172000,4.220850e+01,7.752000
max,514.000000,2018.000000,5.558942e+08,341.260000,139358.000000,7.964521e+06,359278.000000

In [18]:
new_fuel_details.groupby('fuel_type_code_pudl').mean()

,utility_id_ferc1,report_year,fuel_qty_burned,fuel_mmbtu_per_unit,fuel_cost_per_unit_burned,fuel_cost_per_unit_delivered,fuel_cost_per_mmbtu
fuel_type_code_pudl,,,,,,,
coal,115.626530,2004.642067,1.899787e+06,20.755183,67.603187,117.461873,1.787145
gas,123.938774,2005.991691,4.847721e+06,1.022007,13.707197,12.136047,5.410833
nuclear,107.039851,2003.036115,5.496574e+06,17.192529,5047.223037,29151.161702,1.741787
oil,113.204650,2007.185006,6.323899e+04,5.814404,169.045434,314.427940,12.691434
other,105.938931,2000.564885,1.703025e+05,0.100697,20.444221,18.758473,6.118168
waste,154.830664,2005.736842,1.181430e+05,0.343304,19.647350,18.542554,830.235414

In [19]:
# Gas has the lowest average fuel cost per unit burned

In [ ]:
# Question 4

In [20]:
fuel_details.describe()

,utility_id_ferc1,report_year,fuel_qty_burned,fuel_mmbtu_per_unit,fuel_cost_per_unit_burned,fuel_cost_per_unit_delivered,fuel_cost_per_mmbtu
count,29523.000000,29523.000000,2.952300e+04,29523.000000,29523.000000,2.952300e+04,29523.000000
mean,118.601836,2005.806050,2.622119e+06,8.492111,208.649031,9.175704e+02,19.304354
std,74.178353,7.025483,9.118004e+06,10.600220,2854.490090,6.877593e+04,2091.540939
min,1.000000,1994.000000,1.000000e+00,0.000001,-276.080000,-8.749370e+02,-41.501000
25%,55.000000,2000.000000,1.381700e+04,1.024000,5.207000,3.778500e+00,1.940000
50%,122.000000,2006.000000,2.533220e+05,5.762694,26.000000,1.737100e+01,4.127000
75%,176.000000,2012.000000,1.424034e+06,17.006000,47.113000,4.213700e+01,7.745000
max,514.000000,2018.000000,5.558942e+08,341.260000,139358.000000,7.964521e+06,359278.000000

In [21]:
# fuel_mmbtu_per_unit Std = 10.6, 75% percentile = 17.01

In [ ]:
# Question 5

In [30]:
df = fuel_details

In [31]:
skw = (df['fuel_qty_burned'].astype(float).skew())
krt = (df['fuel_qty_burned'].astype(float).kurt())

In [32]:
print("The skewness for the fuel quantity burned in two decimal places?:",(round(skw, 2)))
print("The kurtosis for the fuel quantity burned in two decimal places?:",(round(krt, 2 )))

The skewness for the fuel quantity burned in two decimal places?: 15.85
The kurtosis for the fuel quantity burned in two decimal places?: 651.37

In [22]:
# Question 6

In [23]:
fuel_details.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [24]:
# fuel Unit has a total of 180, percentage is 0.610%

In [25]:
# Here is another way to calculate the total missing

In [26]:
print(fuel_details.isnull().sum().sum())

180

In [27]:
# Question 7

In [28]:
fuel_details.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [29]:
# The missing values are fuel_unit, it is Categorical and Mode imputation can be used since the mean cannot be calculated.

In [ ]:
# Question 8

In [45]:
from scipy import stats

In [46]:
stats.pearsonr(fuel_details['report_year'], fuel_details['fuel_cost_per_unit_burned'])

(0.013599134438134125, 0.01945752000597881)

In [47]:
stats.pearsonr(fuel_details['utility_id_ferc1'], fuel_details['fuel_cost_per_unit_burned'])

(-0.03786270759997259, 7.629687197049137e-11)

In [48]:
stats.pearsonr(fuel_details['fuel_qty_burned'], fuel_details['fuel_cost_per_unit_burned'])

(-0.01853541679482522, 0.0014478305969085916)

In [49]:
stats.pearsonr(fuel_details['fuel_mmbtu_per_unit'], fuel_details['fuel_cost_per_unit_burned'])

(-0.01003380842885307, 0.0847068904758869)

In [50]:
stats.pearsonr(fuel_details['fuel_cost_per_unit_delivered'], fuel_details['fuel_cost_per_unit_burned'])

(0.01100740329916512, 0.058584618609800194)

In [ ]:
# From the above correlation fuel_qty_burned and fuel_mmbtu_per_unit has the second and third lowest correlation with fuel_cost_per_unit_burned

In [33]:
# Question 9

In [35]:
fuel_details.groupby(["report_year","fuel_type_code_pudl"]).count()
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
fuel_details.head()

,record_id,utility_id_ferc1,report_year,plant_name_ferc1,fuel_type_code_pudl,fuel_unit,fuel_qty_burned,fuel_mmbtu_per_unit,fuel_cost_per_unit_burned,fuel_cost_per_unit_delivered,fuel_cost_per_mmbtu
0,f1_fuel_1994_12_1_0_7,1,1994,rockport,coal,ton,5377489.0,16.590,18.59,18.53,1.121
1,f1_fuel_1994_12_1_0_10,1,1994,rockport total plant,coal,ton,10486945.0,16.592,18.58,18.53,1.120
2,f1_fuel_1994_12_2_0_1,2,1994,gorgas,coal,ton,2978683.0,24.130,39.72,38.12,1.650
3,f1_fuel_1994_12_2_0_7,2,1994,barry,coal,ton,3739484.0,23.950,47.21,45.99,1.970
4,f1_fuel_1994_12_2_0_10,2,1994,chickasaw,gas,mcf,40533.0,1.000,2.77,2.77,2.570

In [36]:
fuel_details.groupby(["report_year", "fuel_type_code_pudl"]).sum()

                                 utility_id_ferc1  fuel_qty_burned  \
report_year fuel_type_code_pudl
1994        coal                            50430     7.172082e+08
            gas                             54449     2.432212e+09
            nuclear                          6643     2.069366e+08
            oil                             14821     1.469716e+06
            other                            1208     5.094458e+06
            waste                            3508     1.242241e+06
1995        coal                            51231     1.257398e+09
            gas                             57990     2.570880e+09
            nuclear                          7074     2.054081e+08
            oil                             11329     8.091780e+05
            other                            1307     4.220548e+08
            waste                            3346     1.642051e+06
1996        coal                            45720     6.988514e+08
            gas                             48107     1.915218e+09
            nuclear                          3991     1.487384e+08
            oil                             16639     3.637754e+06
            other                             662     1.144943e+06
            waste                            3162     1.102632e+06
1997        coal                            44254     8.169024e+08
            gas                             50628     2.039925e+09
            nuclear                          3126     1.625564e+08
            oil                             16116     5.384931e+07
            other                            1104     3.211371e+06
            waste                            3325     1.528774e+06
1998        coal                            46403     8.982095e+08
            gas                             57582     2.554651e+09
            nuclear                          6084     1.504636e+08
            oil                              6973     5.436080e+05
            other                            1504     1.157796e+07
            waste                            3053     1.624599e+06
1999        coal                            45126     8.805301e+08
            gas                             54360     2.416453e+09
            nuclear                          6067     1.442885e+08
            oil                              4554     6.400930e+05
            other                            1360     2.324239e+06
            waste                            2167     1.108979e+06
2000        coal                            44271     8.620492e+08
            gas                             56363     2.311988e+09
            nuclear                          5974     1.913320e+08
            oil                             42637     2.315770e+07
            other                            1098     4.302104e+06
            waste                            2175     1.271108e+06
2001        coal                            40232     8.564316e+08
            gas                             55697     2.031479e+09
            nuclear                          5006     2.275242e+08
            oil                             50081     3.030899e+07
            other                             683     7.157700e+05
            waste                            2236     1.361951e+06
2002        coal                            38592     8.144357e+08
            gas                             56660     1.565940e+09
            nuclear                          4414     1.912594e+08
            oil                             42150     1.117958e+07
            other                             993     1.293296e+06
            waste                            2218     1.394020e+06
2003        coal                            38876     8.018815e+08
            gas                             54247     1.262430e+09
            nuclear                          4062     1.881953e+08
            oil                             49381     3.243227e+07
            other                             895     1.099465e+06
            waste                            1856     1.082223e+06
2004        coal                            38246     7.735318e+08
            gas                             51518     1.122867e+09
            nuclear                          3098     1.939959e+08
            oil                             48340     3.127010e+07
            other                             834     2.022104e+06
            waste                            2343     1.110020e+06
2005        coal                            37923     6.046304e+08
            gas                             56055     1.369705e+09
            nuclear                          3881     1.788867e+08
            oil                             52791     8.783487e+07
            other                             712     2.040308e+06
            waste                            2223     1.605762e+06
2006        coal                            37535     6.002375e+08
            gas                             53617     1.586469e+09
            nuclear                          2484     1.880023e+08
            oil                             48154     5.424113e+07
            other                             907     2.100210e+06
            waste                            2956     1.828512e+06
2007        coal                            37444     6.131788e+08
            gas                             55071     1.711543e+09
            nuclear                          1738     1.876135e+08
            oil                             48840     5.689602e+07
            other                             907     1.733797e+06
            waste                            2675     2.153725e+06
2008        coal                            38487     5.752296e+08
            gas                             56471     1.727416e+09
            nuclear                          1947     1.682171e+08
            oil                             48014     3.818744e+07
            other                             907     1.849145e+06
            waste                            2498     2.147651e+06
2009        coal                            37503     5.219981e+08
            gas                             55376     1.905678e+09
            nuclear                          1844     1.848186e+08
            oil                             45188     1.764856e+07
            other                            1098     1.119167e+06
            waste                            3357     2.139046e+06
2010        coal                            36877     5.931191e+08
            gas                             61145     2.250828e+09
            nuclear                          1844     1.886801e+08
            oil                             45133     1.636689e+07
            other                             648     4.894168e+06
            waste                            3142     2.423293e+06
2011        coal                            39557     5.228667e+08
            gas                             60866     2.342867e+09
            nuclear                          2166     1.739756e+08
            oil                             44109     7.172960e+06
            other                             475     3.000340e+06
            waste                            2953     2.169002e+06
2012        coal                            39453     4.833351e+08
            gas                             60688     2.752349e+09
            nuclear                          2005     1.683534e+08
            oil                             44727     5.527834e+06
            other                             517     3.006978e+06
            waste                            2727     2.064520e+06
2013        coal                            38759     5.001244e+08
            gas                             59355     2.607299e+09
            nuclear                          1844     1.656774e+08
            oil                             42662     6.852942e+06
            other                             335     4.387423e+06
            waste                            3422     2.723547e+06
2014        coal                            40106     4.571944e+08
            gas                             59544     2.511089e+09
            nuclear                          2003     1.776633e+08
            oil                             46777     6.968623e+06
            other                              98     5.187094e+06
            waste                            2840     3.607257e+06
2015        coal                            33587     3.878417e+08
            gas                             63840     3.074838e+09
            nuclear                          2750     1.723771e+08
            oil                             37439     6.553111e+06
            other                              98     5.416122e+06
            waste                            2837     3.737472e+06
2016        coal                            30469     3.804213e+08
            gas                             64800     3.265649e+09
            nuclear                          2602     1.610914e+08
            oil                             37127     5.153004e+06
            other                              98     2.763596e+06
            waste                            2547     3.782403e+06
2017        coal                            28995     3.297659e+08
            gas                             60500     2.822875e+09
            nuclear                          2602     1.689084e+08
            oil                             35929     4.296703e+06
            waste                            2183     3.534230e+06
2018        coal                            28278     3.216100e+08
            gas                             60737     3.476148e+09
            nuclear                          2602     1.670945e+08
            oil                             33226     5.975283e+06
            waste                            2277     3.296373e+06

                                 fuel_mmbtu_per_unit  \
report_year fuel_type_code_pudl
1994        coal                        10293.429297
            gas                           498.035534
            nuclear                      1384.184311
            oil                           960.537684
            other                           1.287506
            waste                           0.577288
1995        coal                        10262.019015
            gas                           513.394734
            nuclear                      1365.809151
            oil                           640.517724
            other                           2.363363
            waste                           0.337080
1996        coal                         9269.878000
            gas                           434.236843
            nuclear                      1091.261603
            oil                           929.977902
            other                           0.788831
            waste                           0.364899
1997        coal                         9000.095755
            gas                           456.865725
            nuclear                       809.236891
            oil                           942.374958
            other                           1.953651
            waste                           0.382760
1998        coal                         9212.781694
            gas                           526.381050
            nuclear                      1716.963500
            oil                           391.821612
            other                           2.225648
            waste                           0.221197
1999        coal                         9052.256583
            gas                           502.719878
            nuclear                      1176.120881
            oil                           271.954956
            other                          83.590448
            waste                           0.186733
2000        coal                         8584.171000
            gas                           482.765171
            nuclear                      1178.969954
            oil                          2416.735440
            other                           2.410105
            waste                           0.152991
2001        coal                         7574.081578
            gas                           462.697102
            nuclear                       563.574596
            oil                          2751.141748
            other                           0.056907
            waste                           0.160667
2002        coal                         6967.923735
            gas                           449.771291
            nuclear                       407.179172
            oil                          2173.726548
            other                           0.057613
            waste                           8.665753
2003        coal                         6906.303079
            gas                           409.852719
            nuclear                       341.599992
            oil                          2510.304203
            other                           0.057861
            waste                           8.818894
2004        coal                         6677.321225
            gas                           397.311681
            nuclear                       344.917241
            oil                          2503.990496
            other                           0.042442
            waste                           8.667558
2005        coal                         6712.699417
            gas                           435.390016
            nuclear                       425.500064
            oil                          2742.263128
            other                           0.042440
            waste                           8.653393
2006        coal                         6770.056762
            gas                           436.926437
            nuclear                       337.097262
            oil                          2562.822440
            other                           0.058244
            waste                           8.685188
2007        coal                         6806.668782
            gas                           454.877905
            nuclear                       278.848750
            oil                          2597.730709
            other                           0.059376
            waste                           8.676567
2008        coal                         6577.120958
            gas                           464.612067
            nuclear                       256.055577
            oil                          2385.913270
            other                           0.059582
            waste                           8.663653
2009        coal                         6466.146698
            gas                           463.366662
            nuclear                       130.007730
            oil                          2326.690351
            other                           0.058667
            waste                           8.700041
2010        coal                         6420.927249
            gas                           502.490992
            nuclear                       256.108075
            oil                          2363.706526
            other                           0.183067
            waste                           8.675162
2011        coal                         6535.775560
            gas                           496.808450
            nuclear                       377.170227
            oil                          2236.419038
            other                           0.029524
            waste                           8.662519
2012        coal                         6595.084441
            gas                           491.382392
            nuclear                       319.878187
            oil                          2275.231721
            other                           0.167199
            waste                           8.762649
2013        coal                         6478.798444
            gas                           479.229684
            nuclear                       257.570444
            oil                          2124.105319
            other                           0.152937
            waste                           8.775048
2014        coal                         5932.994198
            gas                           480.452064
            nuclear                       324.910590
            oil                          2138.865405
            other                           0.001414
            waste                           8.715213
2015        coal                         5300.479998
            gas                           482.498621
            nuclear                       258.530724
            oil                          1838.827580
            other                           0.001411
            waste                           8.738479
2016        coal                         4652.271091
            gas                           483.964659
            nuclear                       258.649044
            oil                          1675.542769
            other                           0.001410
            waste                           8.828807
2017        coal                         4343.490065
            gas                           464.722692
            nuclear                       261.401758
            oil                          1655.582813
            waste                           8.686320
2018        coal                         4066.708564
            gas                           466.933475
            nuclear                       260.628340
            oil                          1470.351399
            waste                           8.693921

                                 fuel_cost_per_unit_burned  \
report_year fuel_type_code_pudl
1994        coal                                 14984.572
            gas                                  10792.496
            nuclear                             227983.354
            oil                                   9362.194
            other                                  116.737
            waste                                   52.762
1995        coal                                 14571.785
            gas                                   9087.905
            nuclear                             384152.639
            oil                                  17858.281
            other                                  183.577
            waste                                 -192.699
1996        coal                                 12694.803
            gas                                   1467.390
            nuclear                              66657.887
            oil                                   5357.028
            other                                  160.075
            waste                                   88.092
1997        coal                                 43742.178
            gas                                   1518.471
            nuclear                             112593.911
            oil                                   5387.536
            other                                  153.923
            waste                                  137.433
1998        coal                                 11902.597
            gas                                   7475.596
            nuclear                             117788.269
            oil                                   2608.657
            other                                  225.428
            waste                                  238.109
1999        coal                                 16303.468
            gas                                  16767.895
            nuclear                              62915.808

In [37]:
#Sum fuel_cost_per_unit_burned for fuel type Coal in year 1994
coal_burned_in_1994 = 14984.572
#Sum fuel_cost_per_unit_burned for fuel type Coal in year 1998
coal_burned_in_1998 = 11902.597

In [38]:
percent_change_coal_burned = ((coal_burned_in_1998 - coal_burned_in_1994) / coal_burned_in_1994) * 100

In [39]:
print(percent_change_coal_burned)

-20.567654518260518

In [41]:
#round up to the nearest whole number
print(round(percent_change_coal_burned, 0))

-21.0

In [42]:
# Print Out
print("For fuel type coal, the percentage change in the fuel cost per unit burned in 1998 compared to 1994 is:",(round(percent_change_coal_burned, 0)) ,"%")

For fuel type coal, the percentage change in the fuel cost per unit burned in 1998 compared to 1994 is: -21.0 %

In [43]:
# Question 10

In [44]:
fuel_details.groupby(["report_year"]).mean()

,utility_id_ferc1,fuel_qty_burned,fuel_mmbtu_per_unit,fuel_cost_per_unit_burned,fuel_cost_per_unit_delivered,fuel_cost_per_mmbtu
report_year,,,,,,
1994,106.120648,2.724018e+06,10.638098,213.191996,63.636060,3.086977
1995,110.139051,3.712067e+06,10.644830,354.422555,32.735269,2.868838
1996,108.714154,2.544754e+06,10.778041,79.434995,9196.705948,2.695880
1997,108.366545,2.813503e+06,10.247632,149.482132,11140.197239,3.113486
1998,109.845528,3.267453e+06,10.704964,126.683519,287.154420,2.775862
1999,108.222857,3.281281e+06,10.558885,120.053605,25.551627,2.740251
2000,111.083758,2.472032e+06,9.224475,237.797111,985.362877,4.208403
2001,113.521386,2.321402e+06,8.371469,133.013010,60.050396,4.612658
2002,120.354357,2.145645e+06,8.304833,101.179365,47.594361,6.226281
2003,123.300578,1.888622e+06,8.403746,123.183919,55.663493,7.223933
2004,121.123322,1.782547e+06,8.332425,154.897398,139.524275,8.441597
2005,121.028369,1.768876e+06,8.135972,107.111221,41.438184,9.397078
2006,117.178600,1.957264e+06,8.138090,151.361249,38.657484,10.339898
2007,116.040348,2.035696e+06,8.027581,202.622082,43.325023,10.735181
2008,120.785016,2.046455e+06,7.892854,255.954415,58.588197,12.690115
2009,118.139116,2.154993e+06,7.688192,215.699318,652.694163,10.619376
2010,117.992863,2.423720e+06,7.575013,262.951203,91.862105,8.551217
2011,121.069355,2.461332e+06,7.786182,301.754519,59.774667,9.237591
2012,120.769912,2.747094e+06,7.796063,258.804138,60.994502,8.808904
2013,122.082569,2.741505e+06,7.797024,255.991023,172.307591,9.308225
2014,129.263877,2.700008e+06,7.588334,442.359068,192.737183,10.064673
2015,128.591949,3.340131e+06,7.217820,237.933197,326.535511,8.054361
2016,133.117021,3.693289e+06,6.846478,247.083959,103.901761,6.915613
2017,131.126888,3.352850e+06,6.781353,246.281796,46.196861,368.736351
2018,133.669821,4.178890e+06,6.596546,232.992036,499.269966,7.233643

In [ ]:
# Looking at the years, 1997 has the highest average for fuel_cost_per_unit_delivered